// L6 piano-roll `.pyscript` source generators.
//
// Pure functions: each one takes the operation args and returns a Python
// source string that, when invoked from FL Studio's Piano Roll
// (Ctrl+Alt+Y or the Tools > Macros menu), mutates the current pattern via
// the `flpianoroll` API.
//
// No I/O here — deployer.ts handles file writes. Templates are simple
// string concatenation; piano-roll scripts are read-and-edit safe so we do
// not need elaborate escaping.
//
// flpianoroll unit conventions (encoded in templates):
//   - n.number    : 0..127 MIDI pitch (60 = C4)
//   - n.time      : absolute position in ticks (PPQ-based)
//   - n.length    : duration in ticks
//   - n.velocity  : FLOAT 0.0..1.0 — NOT 0..127. We accept 1..127 at the
//                   MCP boundary and divide by 127.0 inside the generated
//                   script so the LLM never has to think about it.
//
// Each generator emits a header comment block so the deployed file is
// self-documenting when the user opens it in the FL script editor.

export interface PianoRollNote {
  pitch: number;
  position: number;
  length: number;
  velocity: number;
}

function header(operation: string, extra?: string): string {
  const ts = new Date().toISOString();
  const lines = [
    `# Auto-generated by FLStudio-MCP-Goldwep at ${ts}`,
    `# Operation: ${operation}`,
  ];
  if (extra) lines.push(`# ${extra}`);
  lines.push("");
  return lines.join("\n");
}

export function generateAddNotes(notes: PianoRollNote[]): string {
  const tuples = notes
    .map(
      (n) =>
        `        (${n.pitch}, ${n.position}, ${n.length}, ${n.velocity}),`,
    )
    .join("\n");

  return `${header("add_notes", `Notes: ${notes.length}`)}from flpianoroll import score

def main():
    # (pitch, position_ticks, length_ticks, velocity_0_127)
    notes_to_add = [
${tuples}
    ]
    for pitch, pos, length, vel in notes_to_add:
        n = score.Note()
        n.number = pitch
        n.time = pos
        n.length = length
        # flpianoroll velocity is float 0.0..1.0, not MIDI 0..127.
        n.velocity = vel / 127.0
        score.addNote(n)

main()
`;
}

export function generateClearPattern(): string {
  return `${header("clear_pattern")}from flpianoroll import score

def main():
    # score.clearNotes() removes all notes from the current pattern.
    # Iterate-and-remove fallback covered for older API surfaces.
    if hasattr(score, "clearNotes"):
        score.clearNotes()
    else:
        # Remove from end so indices stay valid as we shrink the list.
        for i in range(score.noteCount - 1, -1, -1):
            score.deleteNote(i)

main()
`;
}

export function generateTranspose(semitones: number): string {
  return `${header("transpose", `Semitones: ${semitones}`)}from flpianoroll import score

SEMITONES = ${semitones}

def main():
    for i in range(score.noteCount):
        n = score.getNote(i)
        # Clamp to MIDI range so a giant transpose doesn't wrap or crash.
        new_pitch = max(0, min(127, n.number + SEMITONES))
        n.number = new_pitch

main()
`;
}

export function generateQuantize(gridDivision: number): string {
  // PPQ = 96 in FL Studio's flpianoroll. Snap distance = PPQ / division.
  // The generator emits PPQ as a literal so the script is self-contained
  // and doesn't have to query the host (which has no documented API for
  // PPQ from flpianoroll). 96 is FL's documented internal PPQ for the
  // piano-roll API.
  return `${header("quantize", `Grid division: 1/${gridDivision} (steps per beat)`)}from flpianoroll import score

# FL Studio Piano Roll internal PPQ. Snap distance = PPQ // division.
PPQ = 96
DIVISION = ${gridDivision}
SNAP = PPQ // DIVISION

def main():
    for i in range(score.noteCount):
        n = score.getNote(i)
        # Round-to-nearest snap; floor() would feel laggy on near-grid hits.
        snapped = ((n.time + SNAP // 2) // SNAP) * SNAP
        n.time = snapped

main()
`;
}

export function generateVelocitySet(velocity: number): string {
  return `${header("velocity_set", `Target velocity (MIDI 1..127): ${velocity}`)}from flpianoroll import score

# Generator converts MIDI 1..127 → flpianoroll float 0.0..1.0 once.
TARGET = ${velocity} / 127.0

def main():
    for i in range(score.noteCount):
        n = score.getNote(i)
        n.velocity = TARGET

main()
`;
}
